import test from 'node:test';
import assert from 'node:assert/strict';
import * as e from '../src/game/engine.js';
import {serializePublicRoom,serializePrivatePlayer} from '../src/game/views.js';
function setup(n=2){const r=e.createRoom({hostName:'H',hostSocketId:'s1',hostToken:'t1',code:'ABCDE',mode:'boom'});for(let i=2;i<=n;i++)e.joinRoom(r,{name:'P'+i,socketId:'s'+i,token:'t'+i});for(const p of r.players)e.setReady(r,p.token,true);e.startGame(r,'t1');return r;}
test('boom mode deals safe hands with one rescue kit and n-1 hazards',()=>{for(const n of[2,6]){const r=setup(n);assert.equal(r.mode,'boom');assert.equal(r.deck.filter(c=>c==='live-wire').length,n-1);for(const p of r.players){assert.equal(p.hand.length,5);assert.equal(p.hand.filter(c=>c==='fuse-kit').length,1);assert.equal(p.hand.includes('live-wire'),false);}}});
test('only host can change mode in lobby and all ready flags reset',()=>{const r=setup();e.restartRoom(r,'t1');e.setReady(r,'t1',true);assert.equal(typeof e.setMode,'function');assert.throws(()=>e.setMode(r,'t2','zombie'));assert.throws(()=>e.setMode(r,'t1','bad'));e.setMode(r,'t1','zombie');assert.equal(r.mode,'zombie');assert.ok(r.players.every(p=>!p.ready));});
test('bomb consumes rescue and is returned secretly to deck',()=>{const r=setup(),p=r.players[0];r.deck=['night-vision','live-wire'];e.drawCard(r,p.token);assert.equal(p.eliminated,false);assert.equal(p.hand.includes('fuse-kit'),false);assert.equal(r.deck.filter(c=>c==='live-wire').length,1);assert.equal(r.turnIndex,1);});
test('unprotected bomb eliminates player and determines winner',()=>{const r=setup(),p=r.players[0];p.hand=['night-vision'];r.deck=['live-wire'];e.drawCard(r,p.token);assert.equal(p.eliminated,true);assert.equal(r.phase,'finished');assert.equal(r.winnerToken,'t2');});
test('peek is private and cleared when deck changes',()=>{const r=setup(),p=r.players[0];p.hand=['night-vision'];r.deck=['alley-mix','live-wire','rooftop-hop'];e.playCard(r,'t1','night-vision');assert.deepEqual(serializePrivatePlayer(r,'t1').peek.map(c=>c.id),['rooftop-hop','live-wire','alley-mix']);assert.equal('peek' in serializePublicRoom(r),false);assert.deepEqual(serializePrivatePlayer(r,'t2').peek,[]);e.drawCard(r,'t1');assert.deepEqual(serializePrivatePlayer(r,'t1').peek,[]);});
test('pressure transfers draw debt and skip consumes only one owed draw',()=>{const r=setup();r.players[0].hand=['double-dare'];r.players[1].hand=['rooftop-hop'];e.playCard(r,'t1','double-dare');assert.equal(r.turnIndex,1);assert.equal(r.drawsRemaining,2);e.playCard(r,'t2','rooftop-hop');assert.equal(r.turnIndex,1);assert.equal(r.drawsRemaining,1);r.deck=['night-vision'];e.drawCard(r,'t2');assert.equal(r.turnIndex,0);assert.equal(r.drawsRemaining,1);});
test('boom allows 3 actions and rejects manually playing rescue cards',()=>{const r=setup(),p=r.players[0];p.hand=['fuse-kit','alley-mix','alley-mix','alley-mix','alley-mix'];assert.throws(()=>e.playCard(r,'t1','fuse-kit'));for(let i=0;i<3;i++)e.playCard(r,'t1','alley-mix');assert.throws(()=>e.playCard(r,'t1','alley-mix'));});
test('boom theft validates target before consuming card',()=>{const r=setup();r.players[0].hand=['sticky-paws'];r.players[1].hand=[];const before=JSON.stringify(r);assert.throws(()=>e.playCard(r,'t1','sticky-paws','t2'));assert.equal(JSON.stringify(r),before);r.players[1].hand=['fuse-kit'];e.playCard(r,'t1','sticky-paws','t2');assert.deepEqual(r.players[0].hand,['fuse-kit']);});
test('reconnect preserves mode, private preview and pending draw debt',()=>{const r=setup();r.players[0].hand=['night-vision'];e.playCard(r,'t1','night-vision');const before=serializePrivatePlayer(r,'t1');e.disconnectPlayer(r,'s1');e.reconnectPlayer(r,{token:'t1',socketId:'new'});assert.deepEqual(serializePrivatePlayer(r,'t1'),before);assert.equal(r.mode,'boom');});
test('timeout completes a multiple-draw turn',()=>{const r=setup();r.drawsRemaining=3;r.deck=Array(5).fill('night-vision');e.expireTurn(r,r.turnDeadline+1);assert.equal(r.turnIndex,1);assert.equal(r.deck.length,2);});
test('mode remains selected on rematch and can switch back to zombie rules',()=>{const r=setup();e.restartRoom(r,'t1');assert.equal(r.mode,'boom');e.setMode(r,'t1','zombie');r.players.forEach(p=>e.setReady(r,p.token,true));e.startGame(r,'t1');assert.equal(r.players[0].hp,5);assert.equal(r.players[0].actionPoints,1);assert.equal(r.deck.includes('live-wire'),false);});
