import test from 'node:test';
import assert from 'node:assert/strict';
import * as engine from '../src/game/engine.js';
import {serializePublicRoom, serializePrivatePlayer} from '../src/game/views.js';
function setup(n=2){const r=engine.createRoom({hostName:'A',hostSocketId:'s1',hostToken:'secret-host',code:'ABCDE'});for(let i=2;i<=n;i++)engine.joinRoom(r,{name:`P${i}`,socketId:`s${i}`,token:`secret-${i}`});for(const p of r.players)engine.setReady(r,p.token,true);engine.startGame(r,r.players[0].token);return r;}
test('public views never disclose any reconnect credential',()=>{const r=setup(); const s=JSON.stringify(serializePublicRoom(r));for(const p of r.players)assert.equal(s.includes(p.token),false);assert.ok(serializePublicRoom(r).players.every(p=>p.id));assert.equal(serializePrivatePlayer(r,r.players[0].token).id,r.players[0].id);});
test('offline ready player prevents start',()=>{const r=setup();engine.restartRoom(r,r.players[0].token);for(const p of r.players)engine.setReady(r,p.token,true);engine.disconnectPlayer(r,'s2');assert.throws(()=>engine.startGame(r,r.players[0].token));});
test('zombie deals bonus damage and loses hp after drawing',()=>{const r=setup(),p=r.players[0],t=r.players[1];p.zombie=true;p.infection=3;p.hand=['scratch-frenzy'];engine.playCard(r,p.token,'scratch-frenzy',t.token);assert.equal(t.hp,2);engine.drawCard(r,p.token);assert.equal(p.hp,4);});
test('timeout advances offline turn',()=>{const r=setup();engine.disconnectPlayer(r,'s1');assert.equal(typeof engine.expireTurn,'function');engine.expireTurn(r,r.turnDeadline+1);assert.equal(r.turnIndex,1);});
test('invalid target leaves all game state unchanged',()=>{const r=setup();r.players[0].hand=['scratch-frenzy'];const before=JSON.stringify(r);assert.throws(()=>engine.playCard(r,r.players[0].token,'scratch-frenzy','invalid'));assert.equal(JSON.stringify(r),before);});
test('last survivor wins and antidote reverses zombie',()=>{const r=setup(),p=r.players[0],t=r.players[1];p.zombie=true;p.infection=3;p.hand=['antidote-sardine'];engine.playCard(r,p.token,'antidote-sardine');assert.equal(p.zombie,false);p.actionPoints=1;p.hand=['scratch-frenzy'];t.hp=2;engine.playCard(r,p.token,'scratch-frenzy',t.token);assert.equal(r.phase,'finished');assert.equal(r.winnerToken,p.token);});
test('hand limit prevents unlimited accumulation',()=>{const r=setup(),p=r.players[0];p.hand=Array(10).fill('tuna-patch');engine.drawCard(r,p.token);assert.equal(p.hand.length,10);});
test('invalid trick cannot silently consume a card',()=>{const r=setup(),p=r.players[0],t=r.players[1];p.hand=['alley-swap'];t.hand=[];const before=JSON.stringify(r);assert.throws(()=>engine.playCard(r,p.token,'alley-swap',t.token));assert.equal(JSON.stringify(r),before);});
test('host can remove an offline lobby seat so remaining players can start',()=>{const r=setup(3);engine.restartRoom(r,r.players[0].token);engine.disconnectPlayer(r,'s3');assert.equal(typeof engine.removeOfflinePlayer,'function');assert.throws(()=>engine.removeOfflinePlayer(r,r.players[1].token,r.players[2].id));engine.removeOfflinePlayer(r,r.players[0].token,r.players[2].id);assert.equal(r.players.length,2);});
test('defense and healing apply their documented effects',()=>{const r=setup(),p=r.players[0];p.hand=['trash-shield','tuna-patch','nine-lives'];engine.playCard(r,p.token,'trash-shield');assert.equal(p.guard,2);p.actionPoints=1;p.hp=2;engine.playCard(r,p.token,'tuna-patch');assert.equal(p.hp,4);p.actionPoints=1;engine.playCard(r,p.token,'nine-lives');assert.equal(p.extraLife,1);});
test('trick transfers cards without exposing or creating extra cards',()=>{const r=setup(),p=r.players[0],t=r.players[1];p.hand=['alley-swap','tuna-patch'];t.hand=['trash-shield'];engine.playCard(r,p.token,'alley-swap',t.token);assert.deepEqual(p.hand,['trash-shield']);assert.deepEqual(t.hand,['tuna-patch']);assert.equal(r.discard.at(-1),'alley-swap');});
test('six players deal, cycle and finish after repeated draw-only turns',()=>{const r=setup(6);assert.ok(r.players.every(p=>p.hand.length===5));let steps=0;while(r.phase==='playing'&&steps++<200)engine.drawCard(r,r.players[r.turnIndex].token);assert.equal(r.phase,'finished');assert.equal(r.players.filter(p=>!p.eliminated).length,1);assert.ok(r.players.every(p=>p.hand.length<=10));});
